/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SettingsIndexRouteImport } from './routes/settings/index'
import { Route as PublishIndexRouteImport } from './routes/publish/index'
import { Route as CreationIndexRouteImport } from './routes/creation/index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsIndexRoute = SettingsIndexRouteImport.update({
  id: '/settings/',
  path: '/settings/',
  getParentRoute: () => rootRouteImport,
} as any)
const PublishIndexRoute = PublishIndexRouteImport.update({
  id: '/publish/',
  path: '/publish/',
  getParentRoute: () => rootRouteImport,
} as any)
const CreationIndexRoute = CreationIndexRouteImport.update({
  id: '/creation/',
  path: '/creation/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/creation': typeof CreationIndexRoute
  '/publish': typeof PublishIndexRoute
  '/settings': typeof SettingsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/creation': typeof CreationIndexRoute
  '/publish': typeof PublishIndexRoute
  '/settings': typeof SettingsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/creation/': typeof CreationIndexRoute
  '/publish/': typeof PublishIndexRoute
  '/settings/': typeof SettingsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/creation' | '/publish' | '/settings'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/creation' | '/publish' | '/settings'
  id: '__root__' | '/' | '/creation/' | '/publish/' | '/settings/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CreationIndexRoute: typeof CreationIndexRoute
  PublishIndexRoute: typeof PublishIndexRoute
  SettingsIndexRoute: typeof SettingsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/': {
      id: '/settings/'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/publish/': {
      id: '/publish/'
      path: '/publish'
      fullPath: '/publish'
      preLoaderRoute: typeof PublishIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/creation/': {
      id: '/creation/'
      path: '/creation'
      fullPath: '/creation'
      preLoaderRoute: typeof CreationIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CreationIndexRoute: CreationIndexRoute,
  PublishIndexRoute: PublishIndexRoute,
  SettingsIndexRoute: SettingsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
