apiVersion: agent/v1
kind: Graph
metadata:
  name: analytics
  version: "1.0.0"
  description: "数据分析与洞察工作流"
spec:
  inputs:
    data_source:
      type: string
      required: true
      description: "数据源标识"

  state:
    raw_data:
      type: string
    analysis_result:
      type: string
    report:
      type: string

  nodes:
    - name: collect_data
      tool: llm_generate
      params:
        prompt: "模拟采集来自 '${inputs.data_source}' 的数据。返回 JSON 格式的样例数据。"
      outputs:
        raw_data: "$.data.content"

    - name: analyze_metrics
      tool: llm_generate
      params:
        prompt: "分析以下数据指标，生成洞察:\n${state.raw_data}"
      outputs:
        analysis_result: "$.data.content"

    - name: generate_report
      tool: llm_generate
      params:
        prompt: "基于以下分析结果，生成一份简洁的分析报告:\n${state.analysis_result}"
      outputs:
        report: "$.data.content"

  edges:
    - from: START
      to: collect_data
    - from: collect_data
      to: analyze_metrics
    - from: analyze_metrics
      to: generate_report
    - from: generate_report
      to: END

  outputs:
    report: "${state.report}"
